services:
  db:
    image: mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    env_file:
      - .env
    volumes:
      - lockedu-mysql-db:/var/lib/mysql
    ports:
      - "3307:3306" # Change the first number for different port
    networks:
      - lockedu-network
  api:
    image: lockedu_api
    build: .
    env_file:
      - .env
    ports:
      #- "443:443" # Change the first number for different port
      - "8080:8080" 
    expose:
      #- "443" # 443 is default for https
      - "8080"
    networks:
      - lockedu-network
    depends_on:
      db:
        condition: service_healthy
      
volumes:
  lockedu-mysql-db:
    driver: local

networks:
  lockedu-network:
    driver: bridge
